env: "local"  # local, dev, prod
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"